name: Release
on:
  push:
    branches:
      - master
      - release/*
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
env:
  NODE_VERSION: 14 # Latest LTS
jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Release
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Setup node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Semantic Release
        uses: BrightspaceUI/actions/semantic-release@master
        with:
          GITHUB_TOKEN: ${{ secrets.D2L_GITHUB_TOKEN }}
